[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.backend"

[deploy]
startCommand = "npm start"

[env]
NODE_ENV = "production"
PORT = "5000"
MONGODB_URI = "${{ MONGODB_URI }}"
JWT_SECRET = "${{ JWT_SECRET }}"
